<?php

declare(strict_types=1);

use Bitrix\Main\Localization\Loc;

final class UslovieInDopUsloviya extends CSaleCondCtrl
{
    public static function GetControlID()
    {
        $a=explode('\\', __CLASS__);
        return array_pop($a);
    }

    public static function GetControlDescr()
    {
        return parent::GetControlDescr(); // TODO: Change the autogenerated stub
    }

    public static function GetShowIn($arControls)
    {
        //return [\CSaleActionCtrlBasketGroup::GetControlID()];
        return parent::GetShowIn($arControls);
    }

    public static function GetControlShow($arParams)
    {
        $result = array(
            'controlId' => static::GetControlID(),
            'label' => 'Хуйня',
            'showIn' => static::getShowIn($arParams['SHOW_IN_GROUPS']),
        );

        /*foreach (static::getControls() as $control)
        {
            $result['children'][] = array(
                'controlId' => $control['ID'],
                'group' => false,
                'label' => $control['LABEL'],
                'showIn' => static::getShowIn($params['SHOW_IN_GROUPS']),
                'control' => array(
                    $control['PREFIX'],
                    static::getLogicAtom($control['LOGIC']),
                    static::getValueAtom($control['JS_VALUE'])
                )
            );
        }*/

        return $result;
    }

    public static function GetControls($strControlID = false)
    {
        return [
            'CondUserGroupId' => [
                'ID' => 'CondUserGroupId',
                'FIELD' => 'USER_GROUP_ID',
                'FIELD_TYPE' => 'int',
                'MULTIPLE' => 'N',
                'GROUP' => 'N',
                'LABEL' => 'АЗАЗАЗАЗАЗЗААЗЗАА',
                'PREFIX' => 'АЗАЗАЗАЗАЗЗААЗЗАА',
                'LOGIC' => static::getLogic(array(BT_COND_LOGIC_EQ, BT_COND_LOGIC_NOT_EQ)),
                'JS_VALUE' => array(
                    'type' => 'select',
                    'values' => [
                        1 => 'блевота',
                        2 => 'высер',
                    ],
                    'multiple' => 'Y',
                ),
                'PHP_VALUE' => ''
            ]
        ];
    }
}
